language: php

dist: bionic

notifications:
    email: false

php:
    - "7.1"
    - "7.2"
    - "7.3"
    - "7.4"

services: mysql

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true

env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES=" --prefer-lowest"
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"
    - DOCS_BUILD_BRANCH="OXDEV-3367-schema-docs-generator-spike"

before_install:
    - phpenv config-rm xdebug.ini
    - "npm install -g npm@^2"

install:
    - composer update $DEFAULT_COMPOSER_FLAGS $DEPENDENCIES
    - npm install -g @2fd/graphdoc

script:
    - composer test:syntax
    - composer test:lint
    - composer test:static
    - composer test:unit

after_success:
    - sudo chmod +775 travis.sh
    - ./travis.sh $TRAVIS_BUILD_DIR $TRAVIS_BRANCH $DOCS_BUILD_BRANCH $TRAVIS_PHP_VERSION $DEPENDENCIES

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $jsPrivGithubPage
    keep_history: true
    local_dir: ./deploy/schema
    repo: j-skoczek/j-skoczek.github.io
    target_branch: master
    on:
        branch: $DOCS_BUILD_BRANCH
        condition: $TRAVIS_PHP_VERSION = "7.2" && $DEPENDENCIES = ""
