language: php

dist: bionic

notifications:
    email: false

php:
    - "7.1"
    - "7.2"
    - "7.3"
    - "7.4"

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true

env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES=" --prefer-lowest"
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

before_install:
    - phpenv config-rm xdebug.ini
    - "npm install -g npm@^2"

install:
    - composer update $DEFAULT_COMPOSER_FLAGS $DEPENDENCIES
    - npm install -g @2fd/graphdoc

script:
    - composer test:syntax
    - composer test:lint
    - composer test:static
    - composer test:unit

after_success:
    - sudo sed -e 's|utf8_unicode_ci|latin1_general_ci|g; s|utf8|latin1|g' --in-place /etc/mysql/my.cnf
    - cp source/config.inc.php.dist source/config.inc.php
    - sed -i 's|<dbHost>|localhost|; s|<dbName>|oxideshop|; s|<dbUser>|root|; s|<dbPwd>||; s|<sShopURL>|http://localhost|; s|<sShopDir>|'$TRAVIS_BUILD_DIR'/source|; s|<sCompileDir>|'$TRAVIS_BUILD_DIR'/source/tmp|; s|$this->iDebug = 0|$this->iDebug = 1|' source/config.inc.php
    - sed -i "s|\$this->edition = ''|\$this->edition = 'CE'|" source/config.inc.php
    - graphdoc -e http://localhost/modules/oe/graphql-catalogue/graphdocs.php -o ./doc/schema
    - test -e ~/doc/schema/ && echo file exists || echo file not found
