services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\GraphQL\Catalogue\Controller\:
    resource: 'src/Controller/*'
    public: true

  OxidEsalesGraphQLRepositories:
    namespace: OxidEsales\GraphQL\Catalogue\Service\
    resource: 'src/Service/*Repository.php'

  OxidEsales\GraphQL\Catalogue\Framework\NamespaceMapper:
    class: OxidEsales\GraphQL\Catalogue\Framework\NamespaceMapper
    tags: ['graphql_namespace_mapper']

  OxidEsales\GraphQL\Catalogue\Service\PermissionProvider:
    class: OxidEsales\GraphQL\Catalogue\Service\PermissionProvider
    tags: ['graphql_permission_provider']
