services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\GraphQL\Catalogue\Controller\:
    resource: 'src/Controller/'
    public: true

  OxidEsalesGraphQLCatalogueDataTypeServices:
    namespace: OxidEsales\GraphQL\Catalogue\DataType\
    resource: 'src/DataType/*Service.php'
    public: true

  OxidEsalesGraphQLCatalogueServices:
    namespace: OxidEsales\GraphQL\Catalogue\Service\
    resource: 'src/Service/*.php'
    public: true

  OxidEsales\GraphQL\Catalogue\Framework\NamespaceMapper:
    class: OxidEsales\GraphQL\Catalogue\Framework\NamespaceMapper
    tags: ['graphql_namespace_mapper']

  OxidEsales\GraphQL\Catalogue\Service\PermissionProvider:
    class: OxidEsales\GraphQL\Catalogue\Service\PermissionProvider
    tags: ['graphql_permission_provider']
