services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\GraphQL\Catalogue\Framework\NamespaceMapper:
    class: OxidEsales\GraphQL\Catalogue\Framework\NamespaceMapper
    tags: ['graphql_namespace_mapper']
