services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\GraphQL\Catalogue\Dao\ManufacturerInterface:
    class: OxidEsales\GraphQL\Catalogue\Dao\Manufacturer
    public: true

  OxidEsales\GraphQL\Catalogue\Controller\:
    resource: 'src/Controller/*'
    public: true

  OxidEsales\GraphQL\Catalogue\DataType\:
    resource: 'src/DataType/*Factory.php'
    public: true

  OxidEsales\GraphQL\Catalogue\DataType\CategoryRelationService:
    class: OxidEsales\GraphQL\Catalogue\DataType\CategoryRelationService
    public: true

  OxidEsales\GraphQL\Catalogue\Service\CategoryRepository:
    class: OxidEsales\GraphQL\Catalogue\Service\CategoryRepository

  OxidEsales\GraphQL\Catalogue\Service\ShopRepository:
    class: OxidEsales\GraphQL\Catalogue\Service\ShopRepository

  OxidEsales\GraphQL\Catalogue\Framework\NamespaceMapper:
    class: OxidEsales\GraphQL\Catalogue\Framework\NamespaceMapper
    tags: ['graphql_namespace_mapper']

  OxidEsales\GraphQL\Catalogue\Service\PermissionProvider:
    class: OxidEsales\GraphQL\Catalogue\Service\PermissionProvider
    tags: ['graphql_permission_provider']
