services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\GraphQL\Catalogue\:
    resource: 'src/*'
    exclude: 'src/**/DataType'
    public: true

  OxidEsales\GraphQL\Catalogue\Shared\Service\NamespaceMapper:
    class: OxidEsales\GraphQL\Catalogue\Shared\Service\NamespaceMapper
    tags: ['graphql_namespace_mapper']

  OxidEsales\GraphQL\Catalogue\Shared\Service\PermissionProvider:
    class: OxidEsales\GraphQL\Catalogue\Shared\Service\PermissionProvider
    tags: ['graphql_permission_provider']
